### ISSUE TITLE
Application deploy

### ISSUE THREAD

**Issue by blueberry1312** [blueberry1312/portfolio-microverse-1#8]
I deployed my project earlier than the exercise, so this is the [online version](https://blueberry1312.github.io/portfolio-microverse-1/) of my project. (It is also in the demo link of the readme)

**Comment by osamaashraf6** [comment]
Hi @blueberry1312 , 
# STATUS: APPROVED! 🥇🟢🟢💯 
<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :ship it: 
Congratulations! 🎉 

## Highlights💯🎈🪄✔️

- [x]  Good deploying at the GitHub pages
- [x] Beautiful UI. ✔️
- [x] Nice design.✔️



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
